### ISSUE TITLE
多级路由的文件加载问题

### ISSUE THREAD

**Issue by zhujun24** [CodeLittlePrince/react-webapp-spa#1]
按照作者的思路去实现的时候，发现一个问题，对于多级路由 /detail/:id ，在跳转加载 detail 这个页面的 js 的时候，路径是http://localhost:xxxx/detail/bundle.js，路径多了一个 /detail，然后就 404 ，在
 https://github.com/CodeLittlePrince/react-webapp-spa 里，把 mock 数据的 https://bcy.net/zhipin/detail/xxxx 换成 /detail/xxx 可以复现这个问题。

**Comment by CodeLittlePrince** [comment]
哈哈，因为没有使用router方式跳转啊，这项目本身是用来宣传来着，所以，目的是让用户直接跳 bcy.net。
所以如果你想实现你想要的效果，只需要改一下`components->GoodsList->Item->index.jsx`里的`a`标签就好了。
@zhujun24

**Comment by zhujun24** [comment]
按照你说的的确可以，但是在我写的这个同构项目里面仍然有这个问题。

**Comment by CodeLittlePrince** [comment]
@zhujun24 react其实我很久都没用了，最近一直在弄vue的项目架构，要弄很多东西。同构的话其实网上很多资料的。google 一下 react ssr 或者 react-router v4 ssr tutorial，很多的。我看现在nuxt.js很多人用，可以试试。
等Vue弄的差不多了我回继续把这项目完成，然后回归大React的，嘿嘿~

**Comment by zhujun24** [comment]
👍

**Comment by WangminzeSparkler** [comment]
请问你有找到解决办法吗？我也遇到了同样的问题。

**Comment by WangminzeSparkler** [comment]
> 按照你说的的确可以，但是在我写的这个同构项目里面仍然有这个问题。

请问你有找到解决办法吗？我也遇到了同样的问题。 @zhujun24

**Comment by zhujun24** [comment]
@WangminzeSparkler 暂无解决办法，很久未使用了，爱莫能助
